"""Initial model

Revision ID: 1b39cd751aa1
Revises: a36f62fe062c
Create Date: 2025-11-30 12:43:06.510692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b39cd751aa1'
down_revision = 'a36f62fe062c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_unique_constraint('contact_constraint_01', ['id_type', 'id_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint('contact_constraint_01', type_='unique')

    # ### end Alembic commands ###
